package Package1;
// Generated 1 Nov, 2018 12:08:10 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private BigDecimal rollNo;
     private String name;
     private BigDecimal english;
     private BigDecimal maths;
     private BigDecimal science;

    public Student() {
    }

	
    public Student(BigDecimal rollNo) {
        this.rollNo = rollNo;
    }
    public Student(BigDecimal rollNo, String name, BigDecimal english, BigDecimal maths, BigDecimal science) {
       this.rollNo = rollNo;
       this.name = name;
       this.english = english;
       this.maths = maths;
       this.science = science;
    }
   
    public BigDecimal getRollNo() {
        return this.rollNo;
    }
    
    public void setRollNo(BigDecimal rollNo) {
        this.rollNo = rollNo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getEnglish() {
        return this.english;
    }
    
    public void setEnglish(BigDecimal english) {
        this.english = english;
    }
    public BigDecimal getMaths() {
        return this.maths;
    }
    
    public void setMaths(BigDecimal maths) {
        this.maths = maths;
    }
    public BigDecimal getScience() {
        return this.science;
    }
    
    public void setScience(BigDecimal science) {
        this.science = science;
    }




}


